apiVersion: "config.istio.io/v1alpha2"
kind: rule
metadata:
  name: authz
  namespace: istio-system
spec:
  selector: "true"
  actions:
  - handler: opa-handler.opa.istio-system
    instances:
    - authz-instance.authz.istio-system

---

apiVersion: "config.istio.io/v1alpha2"
kind: authz
metadata:
  name: authz-instance
  namespace: istio-system
spec:
  subject:
    user: source.uid | ""
  action:
    method: request.method | ""
    path: request.path | ""
    headers: request.headers
    destination-namespace: destination.namespace | "default"
    destination-service: destination.service | ""
    source-namespace: source.namespace | "default"
    source-service: source.service | ""
